#!/usr/bin/env python3
"""Maintain the hand-authored English and Simplified Chinese String Catalog entries.

SwiftUI's extractor discovers static strings, but provider actions and status messages
arrive as domain-model values at runtime. This inventory keeps both those dynamic
strings and the translated static strings reproducible. Use --write after extracting
new strings and --check in CI.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys


PROJECT_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = PROJECT_ROOT / "Sources/KeyestroApp/Resources/Localizable.xcstrings"


# Symbolic keys need an explicit English value. English sentence keys fall back to
# their key, so they only need a Chinese translation below.
ENGLISH = {
    "about.version.format": "Keyestro %@ (%@)",
    "clipboard.keyMissing.format": "The encryption key for %lld clipboard items is missing.",
    "clipboard.shortcut.status": "Clipboard shortcut: %@",
    "clipboard.shortcut.unavailable": "Clipboard shortcut unavailable (%d); use the menu bar or record another shortcut.",
    "database.newerSchema.recovery": "Use a version that supports database schema %lld; this build supports %lld.",
    "error.deletion.paths": "Application data paths could not be resolved",
    "error.deletion.partial": "Some local data could not be deleted",
    "extension.preference.clear.confirmation": "Clear %@ for %@?",
    "file.content.match": "Content match · %@",
    "launcher.parameter.required": "%@ is required",
    "launcher.shortcut.status": "Shortcut: %@",
    "launcher.shortcut.unavailable": "Shortcut unavailable (%d); use the menu bar or record another shortcut.",
    "menu.checkUpdates": "Check for Updates…",
    "menu.clipboardHistory.open": "Open Clipboard History",
    "menu.permissions": "Permissions…",
    "menu.permissions.status": "Permissions: Accessibility %@ · Screen Recording %@",
    "onboarding.permissions.explanation": "Window actions and screenshot capture explain their permission at the moment you use them. You can skip those features and grant access later.",
    "quickPaste.shortcut.status": "Quick Paste shortcut: %@",
    "quickPaste.shortcut.unavailable": "Quick Paste shortcut unavailable (%d); record another shortcut in Settings.",
    "quickPaste.success": "Pasted into %@.",
    "scripts.exit.format": "The script exited with code %lld.",
    "scripts.signal.format": "The script was terminated by signal %lld.",
}


ZH_HANS = {
    "%arg non-secret settings merged": "已合并 %arg 项非敏感设置",
    "%arg quick links added · %arg replaced": "新增 %arg 个快捷链接 · 替换 %arg 个",
    "%arg scripts require reconnection · %arg extensions require reinstallation": "%arg 个脚本需要重新连接 · %arg 个扩展需要重新安装",
    "%arg · %arg": "%arg · %arg",
    "1 day": "1 天",
    "30 days or 1,000 items": "30 天或 1,000 项",
    "7 days": "7 天",
    "90 days": "90 天",
    "A backup is written before the transactional quick-link merge.": "事务式合并快捷链接前会先写入备份。",
    "Alpha Application": "Alpha 应用程序",
    "Automatic": "自动",
    "Always confirm before putting this Mac to sleep": "每次让 Mac 睡眠前都确认",
    "Allowed": "已允许",
    "Back": "返回",
    "Benchmark": "基准测试",
    "Browser bundle identifier (optional)": "浏览器 Bundle Identifier（可选）",
    "Calculate and convert units without a network request": "无需联网即可计算并转换单位",
    "Capabilities": "能力",
    "Choose a local .extension directory to inspect it before installation.": "选择本地 .extension 目录，在安装前进行检查。",
    "Clear by Type": "按类型清除",
    "Clear ranking history": "清除排序历史",
    "Clipboard history is off by default and will be encrypted before persistence.": "剪贴板历史默认关闭，持久化前会先加密。",
    "Clipboard capture skipped: %@": "已跳过剪贴板捕获：%@",
    "Clipboard issue": "剪贴板问题",
    "Clipboard retention": "剪贴板保留期限",
    "Clipboard retention could not be applied.": "无法应用剪贴板保留策略。",
    "Clipboard capture was cancelled.": "剪贴板捕获已取消。",
    "Clipboard reading was cancelled.": "剪贴板读取已取消。",
    "An interrupted clipboard capture could not be rolled back.": "无法回滚中断的剪贴板捕获。",
    "Open Privacy settings and review clipboard history before continuing.": "继续前请打开“隐私”设置并检查剪贴板历史。",
    "Clipboard warning": "剪贴板警告",
    "Clipboard Actions": "剪贴板操作",
    "Clipboard actions are unavailable.": "剪贴板操作不可用。",
    "Clipboard content will be pasted into %@.": "剪贴板内容将粘贴到 %@。",
    "Clipboard Encryption Key Is Missing": "剪贴板加密密钥缺失",
    "Clipboard History Is Off": "剪贴板历史已关闭",
    "Clipboard history storage is unavailable.": "剪贴板历史存储不可用。",
    "Clipboard monitoring is paused. Existing history remains available.": "剪贴板监控已暂停。现有历史仍可使用。",
    "Clear All": "全部清除",
    "Clear All Clipboard History…": "清除全部剪贴板历史…",
    "Clear all clipboard history?": "清除全部剪贴板历史？",
    "Clear clipboard history by type?": "按类型清除剪贴板历史？",
    "Clear Current Type…": "清除当前类型…",
    "Copied items matching the current type will appear here.": "与当前类型匹配的已复制项目将显示在这里。",
    "Code signature": "代码签名",
    "Command-number opens visible results": "Command + 数字打开可见结果",
    "Continue": "继续",
    "Current launcher shortcut: %@": "当前启动器快捷键：%@",
    "Delete %arg": "删除 %arg",
    "Delete All Clipboard Items": "删除所有剪贴板项目",
    "Delete File Items": "删除文件项目",
    "Delete Image Items": "删除图像项目",
    "Delete Text Items": "删除文本项目",
    "Delete URL Items": "删除 URL 项目",
    "Delete Undecryptable History and Reinitialize…": "删除无法解密的历史并重新初始化…",
    "Delete all local Keyestro data and quit?": "删除 Keyestro 的全部本地数据并退出？",
    "Delete and Reinitialize Encryption": "删除并重新初始化加密",
    "Delete": "删除",
    "Delete clipboard item?": "删除剪贴板项目？",
    "Done": "完成",
    "Enable /, >, =, and @ query prefixes": "启用 /、>、= 和 @ 查询前缀",
    "Enable Clipboard History": "启用剪贴板历史",
    "Enable clipboard history to save future copied items locally with encryption.": "启用剪贴板历史后，今后复制的项目将以加密方式保存在本地。",
    "Encrypted clipboard metadata is being prepared.": "正在准备加密的剪贴板元数据。",
    "Enabled": "已启用",
    "English": "英语",
    "English + 简体中文": "英语 + 简体中文",
    "Esc": "Esc",
    "Excluded application Bundle IDs (one per line)": "排除的应用 Bundle ID（每行一个）",
    "Executable": "可执行文件",
    "Explicit search: query text is shared only after you open one of this extension’s commands in @ mode.": "显式搜索：仅当你在 @ 模式中打开此扩展的命令后，才会共享查询文本。",
    "Export Preview": "导出预览",
    "Exports contain non-secret settings, quick links, script registration metadata, and extension manifests. They never contain Keychain values, clipboard payloads, script bodies, or private environment values.": "导出内容包含非敏感设置、快捷链接、脚本注册元数据和扩展清单；绝不包含钥匙串值、剪贴板内容、脚本正文或私有环境变量。",
    "Files: %arg": "文件：%arg",
    "Files…": "文件…",
    "Find applications and Spotlight-indexed files": "查找应用和 Spotlight 已索引的文件",
    "Gatekeeper": "Gatekeeper",
    "Gatekeeper and quarantine remain enforced. Keyestro never removes quarantine or bypasses system security.": "Gatekeeper 与隔离机制始终生效。Keyestro 绝不会移除隔离属性或绕过系统安全。",
    "Filter by Type": "按类型筛选",
    "Filter clipboard history (Command-P)": "筛选剪贴板历史（Command-P）",
    "Images…": "图像…",
    "Import Preview": "导入预览",
    "Install and Enable": "安装并启用",
    "Images": "图片",
    "Keyestro does not request Accessibility or Screen Recording during setup.": "Keyestro 不会在设置引导期间请求辅助功能或屏幕录制权限。",
    "about.version.format": "Keyestro %@（构建 %@）",
    "Keyestro remains available from the menu bar when the Dock icon is hidden.": "隐藏 Dock 图标后，仍可从菜单栏使用 Keyestro。",
    "Keyestro keeps only bounded timing samples in memory. Queries, result titles, clipboard content, and file paths are never recorded.": "Keyestro 只在内存中保留有界的计时样本，绝不记录查询、结果标题、剪贴板内容或文件路径。",
    "Keyestro shortcuts must be different.": "Keyestro 的快捷键必须互不相同。",
    "Links": "链接",
    "Loading Clipboard History…": "正在加载剪贴板历史…",
    "Local Performance Diagnostics": "本机性能诊断",
    "Local performance report updated.": "本机性能报告已更新。",
    "onboarding.permissions.explanation": "窗口操作和截图会在使用时说明所需权限。你可以跳过这些功能，稍后再授权。",
    "Local performance samples cleared.": "本机性能样本已清除。",
    "Name": "名称",
    "No Clipboard History": "暂无剪贴板历史",
    "No Matching Clipboard Items": "无匹配的剪贴板项目",
    "Native extensions run with your user permissions. Process isolation protects Keyestro from crashes, but it is not a security sandbox. Install only code you trust.": "原生扩展以你的用户权限运行。进程隔离可保护 Keyestro 不受扩展崩溃影响，但并非安全沙箱。请仅安装你信任的代码。",
    "Native, open source, and local-first. Apache-2.0 licensed.": "原生、开源、本地优先。采用 Apache-2.0 许可证。",
    "Not Allowed": "未允许",
    "No extensions installed": "尚未安装扩展",
    "No timing samples yet. Open and use the launcher, then run the diagnostic again.": "尚无计时样本。请打开并使用启动器，然后再次运行诊断。",
    "Notarization": "公证",
    "Off by default. When enabled, this extension receives queries outside @ mode.": "默认关闭。启用后，此扩展会接收 @ 模式以外的查询。",
    "Open Keyestro shortcut": "打开 Keyestro 的快捷键",
    "Onboarding step %lld of %lld": "引导第 %lld 步，共 %lld 步",
    "Packaged UI Smoke": "打包 UI 冒烟测试",
    "Packaged UI Performance": "打包 UI 性能测试",
    "Packaged Lifecycle": "打包生命周期测试",
    "Path": "路径",
    "Performance report copied without query or result content.": "性能报告已复制，其中不含查询或结果内容。",
    "Permissions are requested only when needed": "仅在需要时请求权限",
    "Quarantine": "隔离状态",
    "Raw queries are never persisted. Clipboard, screenshots, and diagnostics remain local unless you explicitly export them.": "原始查询绝不持久化。除非你明确导出，否则剪贴板、截图和诊断数据始终留在本机。",
    "Remove %arg?": "移除 %arg？",
    "Remove Extension and Managed Files": "移除扩展和托管文件",
    "Remove…": "移除…",
    "Retry": "重试",
    "Run Local Performance Diagnostics": "运行本机性能诊断",
    "Run only the local workflows you explicitly enable": "仅运行你明确启用的本机工作流",
    "Review Before Installing": "安装前检查",
    "SHA-256": "SHA-256",
    "SHA-256 %arg": "SHA-256 %arg",
    "Screenshot OCR uses Vision accurate mode on this Mac and never sends images to a network service.": "截图 OCR 在本机使用 Vision 精确模式，绝不会将图像发送到网络服务。",
    "Scripts are trusted local code with your user permissions. Keyestro copies installed scripts into managed storage and never interpolates arguments into a shell command.": "脚本是以你的用户权限运行的受信任本地代码。Keyestro 会将已安装脚本复制到托管存储，且绝不会把参数插值到 shell 命令中。",
    "Search and act locally": "在本机搜索并执行操作",
    "Security inspection": "安全检查",
    "Share global query text with this extension": "与此扩展共享全局查询文本",
    "Skip setup": "跳过设置",
    "Source": "来源",
    "Copy Performance Report": "复制性能报告",
    "Clear Performance Samples": "清除性能样本",
    "Recent p50 / p95": "最近的 p50 / p95",
    "p50 %@ ms · p95 %@ ms · n=%arg": "p50 %@ 毫秒 · p95 %@ 毫秒 · n=%arg",
    "Tab Next · Esc Back": "Tab 下一项 · Esc 返回",
    "Text…": "文本…",
    "The old encryption key is missing. Existing entries cannot be recovered and will be permanently deleted.": "旧加密密钥已丢失。现有项目无法恢复，并将被永久删除。",
    "The first sleep action always explains its effect. You can keep confirmation enabled for every use.": "首次睡眠操作始终会说明其影响；你也可以保留每次确认。",
    "The source application is inferred best-effort when the clipboard changes; exclusions are a privacy convenience, not a security boundary.": "剪贴板变化时会尽力推断来源应用；排除项只是隐私便利功能，并非安全边界。",
    "The setting could not be saved. The previous value was restored.": "无法保存此设置，已恢复先前有效值。",
    "This permanently deletes the selected encrypted clipboard entries from this Mac.": "这会从此 Mac 永久删除所选的加密剪贴板项目。",
    "This removes the database, caches, clipboard history, managed scripts and extensions, Keychain keys, login item, and preferences. This cannot be undone.": "这会移除数据库、缓存、剪贴板历史、托管脚本与扩展、钥匙串密钥、登录项和偏好设置。此操作无法撤销。",
    "This stops its entire process group and deletes all managed versions. External source files are not changed.": "这会停止其整个进程组并删除所有托管版本。外部源文件不会改变。",
    "Title": "标题",
    "URL template": "URL 模板",
    "URLs…": "URL…",
    "Unlimited items (500 MiB quota)": "不限项目数（500 MiB 配额）",
    "Use Command, Option, or Control with another key. Conflicts remain visible and the menu bar stays available.": "请将 Command、Option 或 Control 与另一个按键组合使用。冲突会保持可见，菜单栏也始终可用。",
    "Use this shortcut from any application. You can change it later in Shortcuts settings.": "可在任意应用中使用此快捷键；稍后也可在“快捷键”设置中更改。",
    "Use placeholders such as {query}; values are percent-encoded.": "使用 {query} 等占位符；值会进行百分号编码。",
    "Welcome to Keyestro": "欢迎使用 Keyestro",
    "Your launcher shortcut": "你的启动器快捷键",
    "macOS requires approval in System Settings → General → Login Items.": "macOS 需要在“系统设置”→“通用”→“登录项”中批准。",
    "⌘%arg": "⌘%arg",
    "日本語": "日语",
    "简体中文": "简体中文",

    # Runtime-derived Quick View labels are not discovered by xcstringstool.
    "Actions": "操作",
    "Choose": "选择",
    "Earlier": "更早",
    "Executing action": "正在执行操作",
    "Open actions": "打开操作",
    "Today": "今天",
    "Yesterday": "昨天",

    # Launcher chrome and accessibility.
    "Action": "操作",
    "Action hint": "操作提示",
    "Add Parameter": "添加参数",
    "All": "全部",
    "Calculator": "计算器",
    "Caches cleared.": "缓存已清除。",
    "Caches could not be cleared.": "无法清除缓存。",
    "Cancelled": "已取消",
    "Choose action": "选择操作",
    "Choice": "选项",
    "Clear Caches": "清除缓存",
    "Choices (comma-separated)": "选项（以逗号分隔）",
    "Commands": "命令",
    "Confirmation required": "需要确认",
    "Configure Script": "配置脚本",
    "Configure…": "配置…",
    "Destructive": "破坏性操作",
    "Directory": "目录",
    "Enter parameters": "输入参数",
    "Extensions": "扩展",
    "File": "文件",
    "Files": "文件",
    "Keywords (comma-separated)": "关键词（以逗号分隔）",
    "Password": "密码",
    "Ready": "就绪",
    "Required": "必填",
    "SF Symbol icon": "SF Symbol 图标",
    "Screen capture region selector": "屏幕截图区域选择器",
    "Searching…": "正在搜索…",
    "Sensitive item": "敏感项目",
    "Sync from Template": "从模板同步",
    "Text": "文本",
    "Start typing to search enabled providers.": "开始输入以搜索已启用的提供器。",
    "The selected action is no longer available": "所选操作已不可用",
    "This action affects something outside Keyestro. Review the target before continuing.": "此操作会影响 Keyestro 之外的内容。继续前请检查目标。",
    "Type": "类型",
    "Save": "保存",
    "Timeout: %arg seconds": "超时：%arg 秒",
    "%lld results": "%lld 个结果",
    "error.deletion.paths": "无法解析应用数据路径",
    "error.deletion.partial": "部分本地数据未能删除",
    "file.content.match": "内容匹配 · %@",
    "Content matches are labeled and rank below file-name matches. Keyestro never requests Full Disk Access automatically.": "内容匹配会明确标注，并排在文件名匹配之后。Keyestro 绝不会自动请求完全磁盘访问权限。",
    "File Search": "文件搜索",
    "Include hidden files": "包含隐藏文件",
    "Include system locations": "包含系统位置",
    "Include the Trash": "包含废纸篓",
    "Search indexed file contents": "搜索已索引的文件内容",
    "launcher.parameter.required": "%@ 为必填项",
    "launcher.shortcut.status": "快捷键：%@",
    "launcher.shortcut.unavailable": "快捷键不可用（%d）；请使用菜单栏或录制其他快捷键。",
    "menu.checkUpdates": "检查更新…",
    "menu.permissions": "权限…",
    "menu.permissions.status": "权限：辅助功能 %@ · 屏幕录制 %@",

    # Built-in action names and messages.
    "Application pinned": "已固定应用",
    "Application unpinned": "已取消固定应用",
    "Bundle identifier copied": "已复制 Bundle ID",
    "Bottom Half": "下半屏",
    "Bottom Left Quarter": "左下四分之一屏",
    "Bottom Right Quarter": "右下四分之一屏",
    "Capture Area and Recognize Text": "截取区域并识别文本",
    "Capture Area to Clipboard": "截取区域到剪贴板",
    "Capture Area to PNG File": "截取区域为 PNG 文件",
    "Center": "居中",
    "Copy": "复制",
    "Copy Bundle Identifier": "复制 Bundle ID",
    "Copy File URL": "复制文件 URL",
    "Copy Path": "复制路径",
    "Copy Result": "复制结果",
    "Copy to Clipboard": "复制到剪贴板",
    "Delete from History": "从历史中删除",
    "Focus Window": "聚焦窗口",
    "Left Half": "左半屏",
    "Maximize": "最大化",
    "Minimized": "已最小化",
    "Move to Next Display": "移到下一台显示器",
    "Open": "打开",
    "Open Accessibility Privacy Settings": "打开辅助功能隐私设置",
    "Open Applications Folder": "打开应用程序文件夹",
    "Open Downloads Folder": "打开下载文件夹",
    "Open Extension Command": "打开扩展命令",
    "Open Home Folder": "打开个人文件夹",
    "Open Link": "打开链接",
    "Open Screen Recording Privacy Settings": "打开屏幕录制隐私设置",
    "Open System Settings": "打开系统设置",
    "Pin or Unpin": "固定或取消固定",
    "Paste into Previous App": "粘贴到先前应用",
    "Paste to Active App": "粘贴到当前应用",
    "OK": "好",
    "Quick Look": "快速查看",
    "Restore Previous Frame": "恢复上一个窗口位置",
    "Result copied": "已复制结果",
    "Results": "结果",
    "Review highlighted-quality output before copying; low-confidence text is never inserted automatically.": "复制前请检查质量较低的识别结果；低置信度文本绝不会自动插入。",
    "Review the local Vision result before copying.": "复制前请检查本机 Vision 的识别结果。",
    "Right Half": "右半屏",
    "Run Script": "运行脚本",
    "Screenshot copied": "已复制截图",
    "Screenshot saved": "已保存截图",
    "Select a region across any display": "在任意显示器上选择区域",
    "Select a region and choose where to save it": "选择区域并指定保存位置",
    "Shown in Finder": "已在 Finder 中显示",
    "Show in Finder": "在 Finder 中显示",
    "Sleep Mac": "让 Mac 进入睡眠",
    "Text recognition complete": "文本识别完成",
    "Top Half": "上半屏",
    "Top Left Quarter": "左上四分之一屏",
    "Top Right Quarter": "右上四分之一屏",
    "Vision OCR runs entirely on this Mac": "Vision OCR 完全在此 Mac 上运行",
    "Window updated": "窗口已更新",
    "Put this Mac to sleep": "让此 Mac 进入睡眠",
    "Open macOS settings": "打开 macOS 设置",
    "Manage window-control permission": "管理窗口控制权限",
    "Manage capture permission": "管理截图权限",
    "Downloads": "下载",
    "Home": "个人文件夹",
    "queries are shared only after opening this command": "仅在打开此命令后共享查询",

    # User-facing domain errors. Codes remain stable and untranslated.
    "A link argument could not be encoded.": "链接参数无法编码。",
    "A migration backup could not be created.": "无法创建迁移备份。",
    "Accessibility permission is required for automatic paste.": "自动粘贴需要辅助功能权限。",
    "Clipboard history could not be cleared.": "无法清除剪贴板历史。",
    "Clipboard history could not be initialized.": "无法初始化剪贴板历史。",
    "Clipboard history could not be reinitialized.": "无法重新初始化剪贴板历史。",
    "Clipboard history is disabled.": "剪贴板历史已停用。",
    "Clipboard history is loading.": "剪贴板历史正在加载。",
    "Clipboard history is not ready.": "剪贴板历史尚未就绪。",
    "Clipboard history is ready.": "剪贴板历史已就绪。",
    "Division by zero is undefined.": "不能除以零。",
    "Drag a region at least 2 × 2 points.": "请拖出至少 2 × 2 点的区域。",
    "Choice parameters need at least one option.": "选项参数至少需要一个选项。",
    "Enter a calculation.": "请输入计算式。",
    "Enter a valid SF Symbol name.": "请输入有效的 SF Symbol 名称。",
    "Every parameter needs a name and title.": "每个参数都需要名称和标题。",
    "Invalid token at position %lld.": "位置 %lld 处的符号无效。",
    "One of the units is not supported.": "其中一个单位不受支持。",
    "Pinning is unavailable.": "固定功能不可用。",
    "Quick links could not be loaded.": "无法加载快捷链接。",
    "Stored data is invalid.": "存储的数据无效。",
    "Text could not be recognized in the selected image.": "无法识别所选图像中的文本。",
    "The application action is invalid.": "应用操作无效。",
    "The application cache path is invalid.": "应用缓存路径无效。",
    "The application cache path is unavailable.": "应用缓存路径不可用。",
    "The application could not be opened.": "无法打开应用。",
    "The application item is invalid.": "应用项目无效。",
    "The calculation action is invalid.": "计算操作无效。",
    "The capture action is unavailable.": "截图操作不可用。",
    "The capture operation failed.": "截图操作失败。",
    "The captured image could not be assembled.": "无法拼合截取的图像。",
    "The clipboard image is invalid or exceeds 100 megapixels.": "剪贴板图像无效或超过 1 亿像素。",
    "The clipboard item could not be decrypted.": "无法解密剪贴板项目。",
    "The clipboard item could not be deleted.": "无法删除剪贴板项目。",
    "The clipboard item could not be saved.": "无法保存剪贴板项目。",
    "The clipboard item failed authentication.": "剪贴板项目认证失败。",
    "The clipboard item was removed.": "剪贴板项目已被移除。",
    "The encrypted clipboard nonce is invalid.": "加密剪贴板的 nonce 无效。",
    "The executable is missing or is not executable.": "可执行文件缺失或不可执行。",
    "The expression contains an unexpected token.": "表达式中包含意外符号。",
    "The expression is incomplete.": "表达式不完整。",
    "The expression is too long or deeply nested.": "表达式过长或嵌套过深。",
    "The extension action failed.": "扩展操作失败。",
    "The extension command is unavailable.": "扩展命令不可用。",
    "The extension did not respond before the deadline.": "扩展未在截止时间前响应。",
    "The extension is disabled.": "扩展已停用。",
    "The extension is no longer installed or enabled.": "扩展已不再安装或启用。",
    "The extension is not authorized for that operation.": "扩展未获授权执行该操作。",
    "The extension package is invalid or unsafe.": "扩展包无效或不安全。",
    "The extension process could not be launched.": "无法启动扩展进程。",
    "The extension process ended unexpectedly.": "扩展进程意外结束。",
    "The extension reported an error.": "扩展报告了错误。",
    "The extension sent invalid protocol data.": "扩展发送了无效协议数据。",
    "The extension uses an incompatible protocol version.": "扩展使用了不兼容的协议版本。",
    "The extension requires a newer version of Keyestro.": "扩展需要更新版本的 Keyestro。",
    "The file could not be opened.": "无法打开文件。",
    "The file item is invalid.": "文件项目无效。",
    "The file query is invalid.": "文件查询无效。",
    "The Keychain item has an invalid format.": "钥匙串项目格式无效。",
    "The local database could not be opened.": "无法打开本地数据库。",
    "The local database could not be upgraded.": "无法升级本地数据库。",
    "The local database operation failed.": "本地数据库操作失败。",
    "The pin state could not be saved.": "无法保存固定状态。",
    "The process could not be launched.": "无法启动进程。",
    "The paste keystroke could not be created.": "无法创建粘贴按键事件。",
    "The previous application could not be activated.": "无法激活先前的应用。",
    "The previous application is no longer available.": "先前的应用已不可用。",
    "The quick link action is invalid.": "快捷链接操作无效。",
    "The script configuration could not be saved.": "无法保存脚本配置。",
    "The script configuration is invalid.": "脚本配置无效。",
    "The quick link could not be opened.": "无法打开快捷链接。",
    "The quick link definition is invalid.": "快捷链接定义无效。",
    "The quick link was removed.": "快捷链接已被移除。",
    "The rendered URL is invalid.": "生成的 URL 无效。",
    "The result could not be copied.": "无法复制结果。",
    "The result is outside the supported numeric range.": "结果超出支持的数值范围。",
    "The selected display is no longer available.": "所选显示器已不可用。",
    "The selected browser is unavailable.": "所选浏览器不可用。",
    "The selected region could not be captured.": "无法截取所选区域。",
    "The selected region is too large to process safely.": "所选区域过大，无法安全处理。",
    "The system command is invalid.": "系统命令无效。",
    "The URL could not be opened.": "无法打开 URL。",
    "The window action failed.": "窗口操作失败。",
    "The window action is invalid.": "窗口操作无效。",
    "The window is no longer available.": "窗口已不可用。",
    "The window operation failed.": "窗口操作失败。",
    "This clipboard image exceeds the 25 MiB limit.": "此剪贴板图像超过 25 MiB 限制。",
    "This clipboard item exceeds the 2 MiB limit.": "此剪贴板项目超过 2 MiB 限制。",
    "Those clipboard items could not be cleared.": "无法清除这些剪贴板项目。",
    "Those units measure different kinds of values.": "这些单位衡量的是不同类型的值。",
    "This window does not support that operation.": "此窗口不支持该操作。",
    "Windows could not be listed.": "无法列出窗口。",

    # Extension preferences, sensitive previews, and runtime-only error messages.
    "Absolute path": "绝对路径",
    "Clear": "清除",
    "Clear the preference and set it again.": "清除该偏好后重新设置。",
    "Enter a new secret": "输入新秘密",
    "Extension preference Keychain values": "扩展偏好的钥匙串值",
    "Hide sensitive preview": "隐藏敏感预览",
    "Login item registration": "登录项注册",
    "Not set": "未设置",
    "Preferences": "偏好设置",
    "Preview hidden": "预览已隐藏",
    "Set": "已设置",
    "Show sensitive preview": "显示敏感预览",
    "Stored in Keychain. When requested, the secret itself is delivered to this trusted extension process; it is never sent in preferencesChanged notifications.": "存储于钥匙串。扩展请求时，秘密本身会交给这个受信任的扩展进程；它绝不会通过 preferencesChanged 通知发送。",
    "Target": "目标",
    "Value": "值",
    "A Keychain item has an invalid length.": "某个钥匙串项目长度无效。",
    "Stored local data is invalid.": "存储的本地数据无效。",
    "A required link argument is missing.": "缺少必填的链接参数。",
    "A required script argument is missing.": "缺少必填的脚本参数。",
    "A script argument is too long.": "脚本参数过长。",
    "A script choice is invalid.": "脚本选项无效。",
    "A script path is invalid.": "脚本路径无效。",
    "A script argument has the wrong type.": "脚本参数类型错误。",
    "An encrypted clipboard thumbnail is incomplete.": "加密的剪贴板缩略图不完整。",
    "An encrypted clipboard thumbnail is invalid.": "加密的剪贴板缩略图无效。",
    "A safe image thumbnail could not be created.": "无法创建安全的图像缩略图。",
    "The extension is unavailable.": "扩展不可用。",
    "The extension did not declare this preference.": "扩展未声明此偏好。",
    "The preference value is invalid.": "偏好值无效。",
    "A stored extension preference is invalid.": "存储的扩展偏好无效。",
    "The extension secret is no longer available in Keychain.": "扩展秘密已不在钥匙串中。",
    "The extension preference could not be restored after a storage failure.": "存储失败后无法恢复扩展偏好。",
    "Review the preference and set it again.": "检查该偏好后重新设置。",
    "The extension preference could not be saved.": "无法保存扩展偏好。",
    "The extension preference could not be cleared.": "无法清除扩展偏好。",
    "A search provider could not complete the search.": "搜索提供器无法完成搜索。",
    "A search provider did not return in time.": "搜索提供器未及时返回。",
    "clipboard.keyMissing.format": "%lld 个剪贴板项目的加密密钥已丢失。",
    "database.newerSchema.recovery": "请使用支持数据库 Schema %lld 的版本；当前版本支持 %lld。",
    "scripts.exit.format": "脚本以退出码 %lld 结束。",
    "scripts.signal.format": "脚本被信号 %lld 终止。",

    # Provider, recovery, and settings strings created outside SwiftUI extraction.
    "A selected display is no longer available.": "所选显示器已不可用。",
    "/Applications": "/Applications",
    "Accessibility": "辅助功能",
    "Applications": "应用",
    "Application Support data": "Application Support 数据",
    "Accessibility permission is required for window management.": "窗口管理需要辅助功能权限。",
    "Allow Keyestro in System Settings → Privacy & Security → Screen Recording.": "请在“系统设置”→“隐私与安全性”→“屏幕与系统录音”中允许 Keyestro。",
    "Allow Keyestro in System Settings → Privacy & Security → Screen Recording. If macOS still reports access as denied, quit and reopen Keyestro.": "请在“系统设置”→“隐私与安全性”→“屏幕与系统录音”中允许 Keyestro。如果 macOS 仍显示未授权，请退出并重新打开 Keyestro。",
    "An application data path escaped its owned directory.": "应用数据路径超出了应用拥有的目录。",
    "Capability denied": "能力未获授权",
    "Check Spotlight settings and try again later.": "请检查 Spotlight 设置，稍后重试。",
    "Check Spotlight status and try again.": "请检查 Spotlight 状态后重试。",
    "Clear older items or increase the quota in settings.": "请清除较旧项目，或在设置中提高配额。",
    "Clipboard history reached its disk quota.": "剪贴板历史已达到磁盘配额。",
    "Clipboard item deleted": "剪贴板项目已删除",
    "Clipboard recovery is not required.": "剪贴板历史无需恢复。",
    "Caches": "缓存",
    "Capture": "截取",
    "Clipboard": "剪贴板",
    "Copied": "已复制",
    "Every URL placeholder must have one argument definition.": "每个 URL 占位符都必须有对应的参数定义。",
    "Export diagnostics and restore a verified backup.": "请导出诊断信息，并恢复已验证的备份。",
    "File URL copied": "文件 URL 已复制",
    "File search failed.": "文件搜索失败。",
    "Invalid params": "参数无效",
    "Keychain could not complete the request.": "钥匙串无法完成请求。",
    "Keychain installation and clipboard keys": "钥匙串中的安装密钥和剪贴板密钥",
    "Method not found": "方法不存在",
    "Open Privacy settings to review recovery options.": "打开“隐私”设置以查看恢复选项。",
    "Open Settings → Permissions to grant access, then refresh.": "打开“设置”→“权限”授予访问权限，然后刷新。",
    "Open Settings → Permissions to grant access, then try again.": "打开“设置”→“权限”授予访问权限，然后重试。",
    "Path copied": "路径已复制",
    "Quick Look could not preview this file.": "快速查看无法预览此文件。",
    "Refresh the application results.": "请刷新应用结果。",
    "Refresh the file results.": "请刷新文件结果。",
    "Refresh the results and try again.": "请刷新结果后重试。",
    "Refresh the search and try again.": "请刷新搜索后重试。",
    "Retry it manually from Extensions settings.": "请在“扩展”设置中手动重试。",
    "Review and reinstall the script before running it.": "请在运行前检查并重新安装该脚本。",
    "Review the recovery screen before deleting or reinitializing clipboard history.": "删除或重新初始化剪贴板历史前，请先检查恢复界面。",
    "Run the search again and choose the current result.": "请重新搜索并选择当前结果。",
    "Run the search again.": "请重新搜索。",
    "Screen Recording": "屏幕录制",
    "Script command": "脚本命令",
    "Scripts": "脚本",
    "Screen Recording access is required.": "需要屏幕录制权限。",
    "Scripts could not be loaded.": "无法加载脚本。",
    "Search for the file again.": "请重新搜索该文件。",
    "Spotlight could not complete the search.": "Spotlight 无法完成搜索。",
    "Spotlight is unavailable or still indexing.": "Spotlight 不可用或仍在建立索引。",
    "System sleep is unavailable.": "系统睡眠不可用。",
    "System Commands": "系统命令",
    "The Mac could not be put to sleep.": "无法使 Mac 进入睡眠。",
    "The action provider is not available.": "操作提供器不可用。",
    "The application has moved or was removed.": "应用已移动或被删除。",
    "The application is no longer installed.": "该应用已不再安装。",
    "The bundle identifier is invalid.": "Bundle Identifier 无效。",
    "The calculation could not be completed.": "无法完成计算。",
    "The clipboard action is invalid.": "剪贴板操作无效。",
    "The clipboard encryption key is missing.": "剪贴板加密密钥缺失。",
    "The clipboard item is invalid.": "剪贴板项目无效。",
    "The extension action is no longer available.": "扩展操作已不可用。",
    "The extension could not be isolated in its own process group.": "无法将扩展隔离到独立进程组。",
    "The extension could not complete the action.": "扩展无法完成操作。",
    "The extension crashed repeatedly and is disabled for this session.": "扩展反复崩溃，已在本次会话中停用。",
    "The extension violated the communication protocol.": "扩展违反了通信协议。",
    "The file action is invalid.": "文件操作无效。",
    "The file result is no longer current.": "文件结果已过期。",
    "The file was moved or deleted.": "文件已移动或删除。",
    "The item could not be written to the clipboard.": "无法将项目写入剪贴板。",
    "The local database is damaged and was left unchanged.": "本地数据库已损坏，且未被修改。",
    "The macOS application data directories are unavailable.": "macOS 应用数据目录不可用。",
    "The merged action target is no longer available.": "合并操作的目标已不可用。",
    "The script action is invalid.": "脚本操作无效。",
    "The script changed after installation.": "脚本在安装后已更改。",
    "The script could not be executed.": "无法执行脚本。",
    "The script definition is invalid.": "脚本定义无效。",
    "The script exceeded its timeout.": "脚本超过了超时时限。",
    "The script is unavailable.": "脚本不可用。",
    "The search result is no longer current.": "搜索结果已过期。",
    "The selected item or action is no longer available.": "所选项目或操作已不可用。",
    "The system location could not be opened.": "无法打开系统位置。",
    "This action was already submitted.": "此操作已提交。",
    "This application has no bundle identifier.": "此应用没有 Bundle Identifier。",
    "This database was created by a newer Keyestro version.": "此数据库由更新版本的 Keyestro 创建。",
    "Try a shorter file name or check Spotlight settings.": "请缩短文件名，或检查 Spotlight 设置。",
    "Try again or disable this provider.": "请重试或停用此提供器。",
    "Try again.": "请重试。",
    "Trusted local script": "受信任的本地脚本",
    "Verify the application is valid and try again.": "请验证应用有效后重试。",
    "The login item setting could not be changed.": "无法更改登录项设置。",
    "The capture operation could not start.": "无法启动截图操作。",
    "Disable the extension or retry it from Extensions settings after updating it.": "请停用该扩展，或更新后在“扩展”设置中重试。",
    "Extensions could not be loaded.": "无法加载扩展。",
    "Managed extension storage is unavailable.": "扩展的托管存储不可用。",
    "The selected directory is not a valid extension package.": "所选目录不是有效的扩展包。",
    "That extension version is already installed.": "该扩展版本已安装。",
    "The extension could not be installed.": "无法安装扩展。",
    "The extension setting could not be saved.": "无法保存扩展设置。",
    "The extension may start again on its next query.": "扩展可能会在下次查询时重新启动。",
    "The extension could not be removed.": "无法移除扩展。",
    "Managed script storage is unavailable.": "脚本的托管存储不可用。",
    "Choose an executable file. The script was not installed.": "请选择可执行文件。脚本未安装。",
    "The script could not be removed.": "无法移除脚本。",
    "Enter a title and an absolute URL template.": "请输入标题和绝对 URL 模板。",
    "The quick link could not be saved.": "无法保存快捷链接。",
    "The quick link is invalid.": "快捷链接无效。",
    "The quick link could not be deleted.": "无法删除快捷链接。",
    "Windows": "窗口",

    # Configuration transactions, trusted-code reconnection, and recovery UI.
    "%arg scripts still require reconnection · %arg extensions still require reinstallation": "%arg 个脚本仍需重新连接 · %arg 个扩展仍需重新安装",
    "%arg unsupported settings ignored": "已忽略 %arg 项不支持的设置",
    "Add Script…": "添加脚本…",
    "Executing action…": "正在执行操作…",
    "Imported Code Requires Confirmation": "导入的代码需要确认",
    "Imported Extensions Requiring Reinstallation": "需要重新安装的导入扩展",
    "Imported Scripts Requiring Reconnection": "需要重新连接的导入脚本",
    "Imported code remains disabled and unavailable until you select and review its local source.": "导入的代码会保持禁用且不可用，直到你选择并检查其本地来源。",
    "Install Managed Copy…": "安装托管副本…",
    "Keyestro will copy the selected executable only if its SHA-256 matches the exported registration.": "仅当所选可执行文件的 SHA-256 与导出的注册信息匹配时，Keyestro 才会复制该文件。",
    "Keyestro will replace the trusted file identity and SHA-256 with the values currently on disk.": "Keyestro 将使用磁盘上的当前值替换受信任的文件身份和 SHA-256。",
    "Learn from successful actions": "从成功操作中学习",
    "Link Original File…": "链接原始文件…",
    "Link this script without copying it?": "不复制并链接此脚本？",
    "Open Permissions Settings": "打开权限设置",
    "Reconfirm Identity and Contents": "重新确认身份和内容",
    "Reconfirm…": "重新确认…",
    "Reconnect %arg?": "重新连接 %arg？",
    "Reconnect Scripts…": "重新连接脚本…",
    "Reconnect…": "重新连接…",
    "Reinstall Extensions…": "重新安装扩展…",
    "Scripts are trusted local code with your user permissions. Managed copies are the default. Linked originals stay in place and must be reconfirmed after their file identity or contents change. Arguments are never interpolated into a shell command.": "脚本是以你的用户权限运行的受信任本地代码。默认使用托管副本。链接的原始文件会留在原处；其文件身份或内容改变后必须重新确认。参数绝不会插值到 shell 命令中。",
    "Select Package…": "选择软件包…",
    "Select and review the exact exported package. Its identifier, version, and SHA-256 must all match.": "请选择并检查导出时对应的软件包；其标识符、版本和 SHA-256 必须全部匹配。",
    "Select the original executable for each registration. Its SHA-256 must match before Keyestro creates a managed copy.": "请为每条注册信息选择原始可执行文件；SHA-256 匹配后，Keyestro 才会创建托管副本。",
    "Tables that could not be fully recovered: %@": "未能完整恢复的表：%@",
    "The file remains at its current path and runs with your user permissions. Keyestro records its identity and SHA-256 and refuses to run it after either changes until you reconfirm.": "该文件会留在当前路径并以你的用户权限运行。Keyestro 会记录其身份和 SHA-256；任一项发生变化后，在你重新确认前都会拒绝运行。",
    "Trust and Link Original": "信任并链接原始文件",
    "Trust the current contents of %arg?": "信任 %arg 的当前内容？",
    "Verify and Reconnect": "验证并重新连接",
    "When disabled, saved usage history is neither applied nor updated. Manual pins still affect ranking.": "停用后，已保存的使用历史既不会用于排序，也不会更新；手动固定仍会影响排序。",
    "The local database could not be prepared.": "无法准备本地数据库。",
    "Review the Backups folder and export diagnostics before changing local data.": "更改本地数据前，请检查 Backups 文件夹并导出诊断信息。",
    "Pending extension reinstallations could not be read.": "无法读取待重新安装的扩展。",
    "The selected package does not match the imported extension registration.": "所选软件包与导入的扩展注册信息不匹配。",
    "Pending script reconnections could not be read.": "无法读取待重新连接的脚本。",
    "Choose an executable file. The linked script was not added.": "请选择可执行文件；链接脚本未添加。",
    "The selected script does not match the imported registration.": "所选脚本与导入的注册信息不匹配。",
    "The linked script could not be reconfirmed.": "无法重新确认链接脚本。",
    "The extension action arguments are invalid.": "扩展操作参数无效。",
    "The damaged local database could not be safely isolated.": "无法安全隔离损坏的本地数据库。",
    "Do not delete the database. Export diagnostics and restore a verified backup.": "请勿删除数据库。请导出诊断信息并恢复经过验证的备份。",
    "A link argument is invalid or too long.": "链接参数无效或过长。",
    "The selected script does not match the exported registration.": "所选脚本与导出的注册信息不匹配。",
    "The script was unregistered, but its managed files could not be deleted.": "脚本已取消注册，但无法删除其托管文件。",
    "Use Delete All Local Data to remove remaining managed files.": "请使用“删除全部本地数据”移除残留的托管文件。",
    "The extension was unregistered, but its installed files could not be deleted.": "扩展已取消注册，但无法删除其已安装文件。",
    "Use Delete All Local Data to remove remaining extension files.": "请使用“删除全部本地数据”移除残留的扩展文件。",
    "Choose the original script, or install this file as a new script.": "请选择原始脚本，或将此文件作为新脚本安装。",
    "The process request contains an invalid argument.": "进程请求包含无效参数。",
    "Ranking history cleared.": "已清除排序历史。",
    "Ranking history could not be cleared.": "无法清除排序历史。",
    "Default settings restored.": "已恢复默认设置。",
    "Default settings could not be restored. Previous values were kept.": "无法恢复默认设置；已保留先前的值。",
    "Default settings could not be restored, and automatic rollback was incomplete. Restore a configuration backup.": "无法恢复默认设置，且自动回滚未完整完成。请恢复配置备份。",
    "Clear %arg for %arg?": "清除 %arg（扩展：%arg）？",
    "Clear Preference": "清除偏好设置",
    "Clear Ranking History": "清除排序历史",
    "Clear all learned ranking history?": "清除全部已学习的排序历史？",
    "Clear ranking history…": "清除排序历史…",
    "Clear…": "清除…",
    "Confirm settings change": "确认设置更改",
    "Delete %arg?": "删除 %arg？",
    "Delete Quick Link": "删除快捷链接",
    "Previous application (currently unavailable)": "上一个应用程序（当前不可用）",
    "Open Clipboard History": "打开剪贴板历史",
    "Open Clipboard History shortcut": "打开剪贴板历史快捷键",
    "Open Privacy Settings": "打开隐私设置",
    "Paste": "粘贴",
    "Paste into Previous App?": "粘贴到上一个应用？",
    "Press a shortcut…": "请按下快捷键…",
    "Remove %arg": "移除 %arg",
    "Remove Script": "移除脚本",
    "Restore Default Settings": "恢复默认设置",
    "Restore all default settings?": "恢复全部默认设置？",
    "Restore default settings…": "恢复默认设置…",
    "Restart Keyestro, then review Privacy settings if the problem continues.": "请重新启动 Keyestro；如果问题仍然存在，请检查“隐私”设置。",
    "Resume Monitoring": "恢复监控",
    "Search Clipboard History": "搜索剪贴板历史",
    "Sensitive content": "敏感内容",
    "Sensitive content, preview hidden": "敏感内容，预览已隐藏",
    "Review the current extension preferences and try again.": "请检查当前扩展偏好设置后重试。",
    "Review the current extension version and confirm removal again.": "请检查当前扩展版本并再次确认移除。",
    "Review the current quick link and confirm deletion again.": "请检查当前快捷链接并再次确认删除。",
    "Review the current script and confirm removal again.": "请检查当前脚本并再次确认移除。",
    "This Mac": "这台 Mac",
    "This permanently deletes all learned usage events from Keyestro's local database. Manual pins are kept.": "这会从 Keyestro 的本地数据库永久删除全部已学习的使用事件；手动固定项会保留。",
    "This permanently deletes the quick link targeting %arg.": "这会永久删除目标为 %arg 的快捷链接。",
    "This permanently removes this extension's saved secret from the Keychain. The secret value is never shown in this confirmation.": "这会从钥匙串永久移除此扩展保存的秘密；确认内容绝不会显示秘密值。",
    "This removes the saved value and notifies the extension that this exact preference is now unset.": "这会移除保存的值，并通知扩展此项偏好设置现已取消设置。",
    "This resets all non-secret Keyestro settings, including both shortcuts and privacy choices. Quicklinks, scripts, extensions, and their saved data are kept.": "这会重置 Keyestro 的全部非敏感设置，包括两个快捷键和隐私选项；快捷链接、脚本、扩展及其保存的数据会保留。",
    "This resets all non-secret Keyestro settings, including all shortcuts and privacy choices. Quicklinks, scripts, extensions, and their saved data are kept.": "这会重置 Keyestro 的全部非敏感设置，包括所有快捷键和隐私选项；快捷链接、脚本、扩展及其保存的数据会保留。",
    "This permanently deletes all encrypted %@ clipboard items from this Mac.": "这会从此 Mac 永久删除所有已加密的 %@ 剪贴板项目。",
    "This permanently deletes all encrypted clipboard items from this Mac.": "这会从此 Mac 永久删除所有已加密的剪贴板项目。",
    "This permanently deletes encrypted clipboard item ID %@.": "这会永久删除 ID 为 %@ 的加密剪贴板项目。",
    "Try another search or clipboard type.": "尝试其他搜索内容或剪贴板类型。",
    "Unknown Source": "未知来源",
    "Choose clipboard type": "选择剪贴板类型",
    "text": "文本",
    "link": "链接",
    "file": "文件",
    "image": "图片",
    "clipboard.shortcut.status": "剪贴板快捷键：%@",
    "clipboard.shortcut.unavailable": "剪贴板快捷键不可用（%d）；请使用菜单栏或录制其他快捷键。",
    "menu.clipboardHistory.open": "打开剪贴板历史",
    "The extension changed after the removal confirmation.": "确认移除后，扩展已发生变化。",
    "The extension changed after this preference was reviewed.": "检查此偏好设置后，扩展已发生变化。",
    "The quick link changed after the deletion confirmation.": "确认删除后，快捷链接已发生变化。",
    "The script changed after the removal confirmation.": "确认移除后，脚本已发生变化。",
    "The sensitive action does not identify a safe confirmation target.": "此敏感操作未提供可安全显示的确认目标。",
    "Refresh the results or use a different action.": "请刷新结果或改用其他操作。",
    "extension": "扩展",
    "extension preference": "扩展偏好设置",
    "extension.preference.clear.confirmation": "清除 %@（扩展：%@）？",
    "Quick Paste": "快速粘贴",
    "Quick Paste Latest Text": "快速粘贴最新文本",
    "Quick Paste latest text shortcut": "快速粘贴最新文本快捷键",
    "Enable Quick Paste for the latest text or URL": "启用快速粘贴最新文本或 URL",
    "Allow sensitive-looking text": "允许疑似敏感文本",
    "Record a unique Quick Paste shortcut in Shortcuts before it can run.": "请先在“快捷键”中录制一个唯一的快速粘贴快捷键。",
    "The shortcut writes the newest history item to the clipboard and sends Command-V only if the same destination app remains frontmost. Images, files, and blocked sensitive items open Clipboard History instead.": "该快捷键会将最新历史项写入剪贴板，并且仅当同一目标应用仍在前台时发送 Command-V；图片、文件和被阻止的敏感项会改为打开剪贴板历史。",
    "Review Accessibility Permission": "检查辅助功能权限",
    "Enable Quick Paste?": "启用快速粘贴？",
    "Enable": "启用",
    "Quick Paste requires Accessibility permission to send Command-V to the frontmost app. It may paste sensitive clipboard text unless you turn off “Allow sensitive-looking text.”": "快速粘贴需要辅助功能权限，才能向前台应用发送 Command-V。除非关闭“允许疑似敏感文本”，否则它可能粘贴敏感剪贴板文本。",
    "Record Shortcut…": "录制快捷键…",
    "Enable Quick Paste and record its shortcut in Keyestro Settings.": "请在 Keyestro 设置中启用快速粘贴并录制快捷键。",
    "Keep the destination application and field frontmost, then try again.": "请让目标应用和输入框保持在前台，然后重试。",
    "Clipboard history is unavailable. Enable it in Keyestro Settings and copy an item first.": "剪贴板历史不可用。请在 Keyestro 设置中启用它，并先复制一个项目。",
    "Clipboard history is empty. Copy text or a URL, then try again.": "剪贴板历史为空。请复制文本或 URL 后重试。",
    "Clipboard history is unavailable. Enable it in Keyestro Settings and try again.": "剪贴板历史不可用。请在 Keyestro 设置中启用后重试。",
    "Quick Paste supports text and URLs. Choose the latest item in Clipboard History instead.": "快速粘贴仅支持文本和 URL。请改在剪贴板历史中选择最新项目。",
    "Sensitive-looking content was not pasted. Review it in Clipboard History instead.": "疑似敏感内容未被粘贴。请改在剪贴板历史中检查。",
    "Quick Paste was cancelled before sending a keystroke.": "快速粘贴已在发送按键前取消。",
    "Accessibility permission is required. Open Keyestro Settings → Permissions, grant access, and try again.": "需要辅助功能权限。请打开 Keyestro 设置 → 权限，授权后重试。",
    "Paste was cancelled because the frontmost application changed. Return to the destination field and try again.": "由于前台应用发生变化，粘贴已取消。请返回目标输入框后重试。",
    "The destination application is unavailable. Keep it open and frontmost, then try again.": "目标应用不可用。请保持其打开并置于前台，然后重试。",
    "The target application is no longer available.": "目标应用已不可用。",
    "Keep the destination application open and frontmost, then try again.": "请保持目标应用打开并置于前台，然后重试。",
    "The target application could not be activated.": "无法激活目标应用。",
    "The frontmost application changed before paste.": "粘贴前，前台应用已发生变化。",
    "Return to the destination field and try again.": "请返回目标输入框后重试。",
    "quickPaste.shortcut.status": "快速粘贴快捷键：%@",
    "quickPaste.shortcut.unavailable": "快速粘贴快捷键不可用（%d）；请在设置中录制其他快捷键。",
    "quickPaste.success": "已粘贴到 %@。",
    "%lld actions": "%lld 个操作",
    "%lld clipboard types": "%lld 种剪贴板类型",
    "%lld items · grouped by date": "%lld 项 · 按日期分组",
    "Application": "应用程序",
    "Appearance": "外观",
    "Auto follows the macOS appearance. A Light or Dark override is saved on this Mac.": "自动模式跟随 macOS 外观；浅色或深色手动覆盖会保存在此 Mac 上。",
    "Built-in sources stay on this Mac": "内置来源始终留在此 Mac",
    "CLIPBOARD · LOCAL": "剪贴板 · 本地",
    "Clipboard history is encrypted and searched on device.": "剪贴板历史会在设备上加密并搜索。",
    "Command": "命令",
    "Encrypted on this Mac": "已在此 Mac 上加密",
    "FILE": "文件",
    "Files, apps, and clipboard are indexed on device.": "文件、应用和剪贴板均在设备上建立索引。",
    "Files, apps, and clipboard are searched on device.": "文件、应用和剪贴板均在设备上搜索。",
    "Image": "图片",
    "LOCAL INDEX · READY": "本地索引 · 就绪",
    "LOCAL SOURCES · READY": "本地来源 · 就绪",
    "Launcher appearance": "启动器外观",
    "Link": "链接",
    "Local": "本地",
    "Markdown": "Markdown",
    "Never leaves this Mac": "永不离开此 Mac",
    "Open file": "打开文件",
    "Private sources stay hidden": "私密来源保持隐藏",
    "QUICK VIEW": "快速预览",
    "Recent Files": "最近文件",
    "Reveal only after explicit permission": "仅在明确授权后显示",
    "Reveal only after explicit selection": "仅在明确选择后显示",
    "Select a clipboard item to preview it": "选择剪贴板项目以预览",
    "Select a result to preview it": "选择结果以预览",
    "Sensitive previews stay hidden": "敏感内容预览保持隐藏",
    "↩": "↩",
    "⌘ P": "⌘ P",
    "⌘↩": "⌘↩",
}


def localized_unit(value: str) -> dict[str, object]:
    return {"stringUnit": {"state": "translated", "value": value}}


def load_catalog() -> dict[str, object]:
    with CATALOG_PATH.open(encoding="utf-8") as source:
        return json.load(source)


def problems(catalog: dict[str, object]) -> list[str]:
    strings = catalog.get("strings")
    if not isinstance(strings, dict):
        return ["catalog has no strings object"]

    failures: list[str] = []
    for key, value in ENGLISH.items():
        entry = strings.get(key)
        actual = entry.get("localizations", {}).get("en") if isinstance(entry, dict) else None
        if actual != localized_unit(value):
            failures.append(f"English localization is missing or stale: {key}")
    for key, value in ZH_HANS.items():
        entry = strings.get(key)
        actual = entry.get("localizations", {}).get("zh-Hans") if isinstance(entry, dict) else None
        if actual != localized_unit(value):
            failures.append(f"Simplified Chinese localization is missing or stale: {key}")

    for key, entry in strings.items():
        if not isinstance(entry, dict):
            failures.append(f"invalid catalog entry: {key}")
            continue
        if "zh-Hans" not in entry.get("localizations", {}):
            failures.append(f"extracted string has no Simplified Chinese localization: {key}")

    runtime_patterns = (
        re.compile(r'\bmessage:\s*"([^"\\]*(?:\\.[^"\\]*)*)"'),
        re.compile(r'\brecoverySuggestion:\s*"([^"\\]*(?:\\.[^"\\]*)*)"'),
        re.compile(r'\berror\s*=\s*"([^"\\]*(?:\\.[^"\\]*)*)"'),
        re.compile(r'\.success\(message:\s*"([^"\\]*(?:\\.[^"\\]*)*)"'),
        re.compile(r'\b(?:title|subtitle|displayName):\s*"([^"\\]*(?:\\.[^"\\]*)*)"'),
    )
    for source_path in sorted((PROJECT_ROOT / "Sources").rglob("*.swift")):
        source = source_path.read_text(encoding="utf-8")
        for pattern in runtime_patterns:
            for match in pattern.finditer(source):
                key = match.group(1)
                if r"\(" in key:
                    continue
                entry = strings.get(key)
                if not isinstance(entry, dict) or "zh-Hans" not in entry.get("localizations", {}):
                    relative = source_path.relative_to(PROJECT_ROOT)
                    line = source.count("\n", 0, match.start()) + 1
                    failures.append(f"runtime string has no Simplified Chinese localization: {relative}:{line}: {key}")
    return failures


def merge(catalog: dict[str, object]) -> None:
    strings = catalog.setdefault("strings", {})
    if not isinstance(strings, dict):
        raise ValueError("catalog strings value is not an object")

    for language, inventory in (("en", ENGLISH), ("zh-Hans", ZH_HANS)):
        for key, value in inventory.items():
            entry = strings.setdefault(key, {})
            localizations = entry.setdefault("localizations", {})
            localizations[language] = localized_unit(value)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="verify that the catalog matches the inventory")
    mode.add_argument("--write", action="store_true", help="merge the inventory into the catalog")
    arguments = parser.parse_args()

    catalog = load_catalog()
    if arguments.write:
        merge(catalog)
        CATALOG_PATH.write_text(
            json.dumps(catalog, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    failures = problems(catalog)
    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    print(f"Localization catalog verified ({len(catalog['strings'])} keys).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
